debug: false
max_workers: 8
tesseract_path: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
reroll:
  pack: "PALKIA"
  delay_ms: 300
  game_speed: 3
  swipe_speed: 480
  confidence: 0.8
  timeout: 45
  language: "Chinese"
  account_name: "SlvGP"
  max_packs_to_open: 4
  check_double_twostar: false
adb_ports:
  - "16416"
  - "16448"
  - "16480"
  - "16512"
  - "16544"
  - "16576"

friend_codes:
  use_remote: true
  remote_friend_codes:
    url: "http://example.com"
    username: "your_username"
    password: "your_password"
  use_local: false
  local_friend_codes:
    path: "friend_codes.json"

discord:
  use_webhook: true
  webhook_url: "https://discord.com/api/webhooks"
  user_id: "1234567890"
  heat_beat_url: "https://discord.com/api/webhooks"
